### ISSUE TITLE
typos in the version catalogs FAQ

### ISSUE THREAD

**Issue by jnizet** [melix/blog#10]
Hi Cedric. Thanks for the FAQ on the version catalogs.
I spotted the following typos in the article (which doesn't seem to be pushed in this repo yet):

- "You I use a platform or a catalog?" should be "Should I use a platform or a catalog?"
- `libs.getUnit().getJupiter()` should be `libs.getJunit().getJupiter()`
- formatting issue in "you’re implicitly creating a group of dependencies` called _commons"
- "in why subtree to look at" should be "which subtree to look at"
- "that you want to use your own" should be "if you want to use your own"

**Comment by melix** [comment]
Thanks, I had already fixed all but the last one :)
